language: node_js
branches:
  except:
    - latest
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- ./create_config.sh
- gem install cucumber aruba
script:
- npm test
- cucumber -t ~@wip
- ./bin/category-sync -p ${SPHERE_PROJECT_KEY} import -f data/minimum-header.csv
notifications:
  hipchat:
    rooms:
    template:
    - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: change
env:
  global:
branches:
  except:
  - latest
